### ISSUE TITLE
Code hints are sometimes displayed in reverse

### ISSUE THREAD

**Issue by le717** [mackenza/Brackets-PHP-SmartHints#26]
Sometimes, the code hints appear in reverse order when compared to JS code hints:

![js-hint-order](https://cloud.githubusercontent.com/assets/3382464/6082737/86f60156-adf1-11e4-994f-ace6c18f7f85.png)

That is how I expect the order to be, but sometimes (not all the time) the PHP hints are like this:

![php-hint-order](https://cloud.githubusercontent.com/assets/3382464/6082770/bb8535cc-adf1-11e4-8e24-b88bb0c2b660.png)

The weird thing is, recreating the JS case will produce the desired order, but in my (learning) PHP scripts, it occasionally appears as the image above or the desired order.

I can the homework script this is occurring in if you need me to.

**Comment by mackenza** [comment]
I have seen this before and I think I had tried to address it but never really figured out what the problem is.  I have `.sort()` as the last thing I do before returning the word list arrays, so I would have thought this was covered but apparently it doesn't always work :)

Let me have another look and I will put updates to my findings in this issue. 

Thanks for the bug report.

**Comment by mackenza** [comment]
@le717 I was looking at this and noticed something about your two screen shots:

In the JS one you have:
```
addresses
addressesCount
```
in the PHP you don't compare the same.  You have:
```
$addressCount
$addresses
```
so that appears correct in that `C` comes before `e`.

Is this just a mistake in your example or are there other anomalies that need to be looked at?

**Comment by le717** [comment]
...

My bad. I just tried it again now with matching variables and it's correct. I saw this last night, and I apparently was not fully comprehending the issue is my fault.

Sorry about that.
